local M = {}

function M.get(c, opts)
  return {
    -- UI
    AerialNormal = { fg = c.fg },
    AerialNormalFloat = { fg = c.fg, bg = c.float_bg },
    AerialLine = { bg = c.bg_highlight },
    AerialLineNC = { bg = c.bg_highlight },
    AerialGuide = { fg = c.fg_dim },
    AerialPrivate = { fg = c.fg_muted },
    AerialProtected = { fg = c.fg_muted },

    -- Symbol kind text (label next to icon)
    AerialArray = { fg = c.fg },
    AerialBoolean = { fg = c.fg },
    AerialClass = { fg = c.fg },
    AerialConstant = { fg = c.fg },
    AerialConstructor = { fg = c.fg },
    AerialEnum = { fg = c.fg },
    AerialEnumMember = { fg = c.fg },
    AerialEvent = { fg = c.fg },
    AerialField = { fg = c.fg },
    AerialFile = { fg = c.fg },
    AerialFunction = { fg = c.fg },
    AerialInterface = { fg = c.fg },
    AerialKey = { fg = c.fg },
    AerialMethod = { fg = c.fg },
    AerialModule = { fg = c.fg },
    AerialNamespace = { fg = c.fg },
    AerialNull = { fg = c.fg },
    AerialNumber = { fg = c.fg },
    AerialObject = { fg = c.fg },
    AerialOperator = { fg = c.fg },
    AerialPackage = { fg = c.fg },
    AerialProperty = { fg = c.fg },
    AerialString = { fg = c.fg },
    AerialStruct = { fg = c.fg },
    AerialTypeParameter = { fg = c.fg },
    AerialVariable = { fg = c.fg },

    -- Symbol kind icons
    AerialArrayIcon = { fg = c.orange },
    AerialBooleanIcon = { fg = c.red },
    AerialClassIcon = { fg = c.purple },
    AerialConstantIcon = { fg = c.red },
    AerialConstructorIcon = { fg = c.blue },
    AerialEnumIcon = { fg = c.purple },
    AerialEnumMemberIcon = { fg = c.orange },
    AerialEventIcon = { fg = c.orange },
    AerialFieldIcon = { fg = c.orange },
    AerialFileIcon = { fg = c.fg },
    AerialFunctionIcon = { fg = c.blue },
    AerialInterfaceIcon = { fg = c.purple },
    AerialKeyIcon = { fg = c.orange },
    AerialMethodIcon = { fg = c.blue },
    AerialModuleIcon = { fg = c.blue },
    AerialNamespaceIcon = { fg = c.blue },
    AerialNullIcon = { fg = c.red },
    AerialNumberIcon = { fg = c.red },
    AerialObjectIcon = { fg = c.purple },
    AerialOperatorIcon = { fg = c.yellow },
    AerialPackageIcon = { fg = c.blue },
    AerialPropertyIcon = { fg = c.orange },
    AerialStringIcon = { fg = c.green },
    AerialStructIcon = { fg = c.purple },
    AerialTypeParameterIcon = { fg = c.purple },
    AerialVariableIcon = { fg = c.pink },
  }
end

return M
