local M = {}

function M.get(c, opts)
  local transparent = opts.transparent
  local dim_inactive = opts.dim_inactive

  return {
    -- Editor UI
    Normal = { fg = c.fg, bg = transparent and c.none or c.bg },
    NormalFloat = { fg = c.fg, bg = transparent and c.none or c.bg_float },
    NormalNC = { fg = c.fg, bg = dim_inactive and c.bg_dark or (transparent and c.none or c.bg) },
    Cursor = { fg = c.bg, bg = c.fg },
    lCursor = { fg = c.bg, bg = c.fg },
    CursorIM = { fg = c.bg, bg = c.fg },
    CursorLine = { bg = c.bg_highlight },
    CursorColumn = { bg = c.bg_highlight },
    CursorLineNr = { fg = c.yellow },
    LineNr = { fg = c.fg_gutter },
    SignColumn = { fg = c.fg_gutter, bg = transparent and c.none or c.bg },
    VertSplit = { fg = c.bg_visual },
    WinSeparator = { fg = c.bg_visual },
    Folded = { fg = c.fg_dim, bg = c.bg_highlight },
    FoldColumn = { fg = c.fg_gutter, bg = transparent and c.none or c.bg },
    StatusLine = { fg = c.fg, bg = c.bg_status },
    StatusLineNC = { fg = c.fg_dim, bg = c.bg_dark },
    TabLine = { fg = c.fg_dim, bg = c.bg_dark },
    TabLineFill = { bg = c.bg_darker },
    TabLineSel = { fg = c.fg, bg = c.bg },
    WinBar = { fg = c.fg, bg = transparent and c.none or c.bg },
    WinBarNC = { fg = c.fg_dim, bg = dim_inactive and c.bg_dark or (transparent and c.none or c.bg) },
    Pmenu = { fg = c.fg, bg = c.bg_popup },
    PmenuSel = { bg = c.bg_visual },
    PmenuSbar = { bg = c.bg_popup },
    PmenuThumb = { bg = c.fg_gutter },
    FloatBorder = { fg = c.fg_gutter, bg = transparent and c.none or c.bg_float },
    FloatTitle = { fg = c.blue, bg = transparent and c.none or c.bg_float },
    WildMenu = { fg = c.fg, bg = c.bg_visual },
    Search = { fg = c.bg, bg = c.cyan },
    IncSearch = { fg = c.bg, bg = c.cyan },
    CurSearch = { fg = c.bg, bg = c.sun, bold = true },
    Visual = { bg = c.bg_visual },
    VisualNOS = { bg = c.bg_visual },
    MatchParen = { fg = c.orange, bold = true, underline = true },
    ModeMsg = { fg = c.fg, bold = true },
    MoreMsg = { fg = c.blue },
    Question = { fg = c.blue },
    WarningMsg = { fg = c.warning },
    ErrorMsg = { fg = c.error },
    Title = { fg = c.blue, bold = true },
    Directory = { fg = c.blue },
    NonText = { fg = c.fg_dim },
    SpecialKey = { fg = c.fg_dim },
    Conceal = { fg = c.fg_dim },
    ColorColumn = { bg = c.bg_highlight },
    Whitespace = { fg = c.fg_dim },
    EndOfBuffer = { fg = c.bg },
    QuickFixLine = { bg = c.bg_highlight, bold = true },
    SpellBad = { undercurl = true, sp = c.error },
    SpellCap = { undercurl = true, sp = c.warning },
    SpellLocal = { undercurl = true, sp = c.info },
    SpellRare = { undercurl = true, sp = c.hint },

    -- Syntax (matched to Bearded Theme scopes.ts)
    Comment = vim.tbl_extend("force", { fg = c.fg_dim }, opts.styles.comments),
    Constant = { fg = c.red },
    String = vim.tbl_extend("force", { fg = c.green }, opts.styles.strings),
    Character = { fg = c.green },
    Number = { fg = c.red },
    Boolean = { fg = c.red },
    Float = { fg = c.red },
    Identifier = vim.tbl_extend("force", { fg = c.pink }, opts.styles.variables),
    Function = vim.tbl_extend("force", { fg = c.blue }, opts.styles.functions),
    Statement = { fg = c.yellow },
    Conditional = vim.tbl_extend("force", { fg = c.yellow }, opts.styles.keywords),
    Repeat = vim.tbl_extend("force", { fg = c.yellow }, opts.styles.keywords),
    Label = { fg = c.pink },
    Operator = { fg = c.yellow },
    Keyword = vim.tbl_extend("force", { fg = c.yellow }, opts.styles.keywords),
    Exception = vim.tbl_extend("force", { fg = c.yellow }, opts.styles.keywords),
    PreProc = { fg = c.yellow },
    Include = { fg = c.yellow },
    Define = { fg = c.yellow },
    Macro = { fg = c.yellow },
    PreCondit = { fg = c.yellow },
    Type = { fg = c.purple },
    StorageClass = { fg = c.cyan },
    Structure = { fg = c.purple },
    Typedef = { fg = c.purple },
    Special = { fg = c.pink },
    SpecialChar = { fg = c.pink },
    Tag = { fg = c.blue },
    Delimiter = { fg = c.fg_muted },
    SpecialComment = { fg = c.fg_dim, italic = true },
    Debug = { fg = c.orange },
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Ignore = { fg = c.bg },
    Error = { fg = c.error },
    Todo = { fg = c.bg, bg = c.yellow, bold = true },
    Added = { fg = c.green },
    Changed = { fg = c.yellow },
    Removed = { fg = c.red },

    -- Diagnostics
    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warning },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticOk = { fg = c.success },
    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warning },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },
    DiagnosticVirtualTextError = { fg = c.error, bg = c.bg_dark },
    DiagnosticVirtualTextWarn = { fg = c.warning, bg = c.bg_dark },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = c.bg_dark },
    DiagnosticVirtualTextHint = { fg = c.hint, bg = c.bg_dark },
    DiagnosticSignError = { fg = c.error },
    DiagnosticSignWarn = { fg = c.warning },
    DiagnosticSignInfo = { fg = c.info },
    DiagnosticSignHint = { fg = c.hint },

    -- LSP
    LspReferenceText = { bg = c.bg_highlight },
    LspReferenceRead = { bg = c.bg_highlight },
    LspReferenceWrite = { bg = c.bg_highlight, bold = true },
    LspSignatureActiveParameter = { fg = c.orange, bold = true },
    LspInfoBorder = { fg = c.fg_gutter, bg = c.bg_float },

    -- Diff
    DiffAdd = { bg = "#192d24" },
    DiffChange = { bg = "#242833" },
    DiffDelete = { bg = "#351c22" },
    DiffText = { bg = "#334559" },
    diffAdded = { fg = c.green },
    diffChanged = { fg = c.yellow },
    diffRemoved = { fg = c.red },
    diffFile = { fg = c.blue, bold = true },
    diffLine = { fg = c.fg_dim },
    diffIndexLine = { fg = c.purple },
  }
end

return M
